services:
  diariolx-postgres-test:
    container_name: diariolx-postgres-test
    image: diariolx-postgres-test
    env_file:
      - ../../.env.staging
    ports:
      - 5435:5432
    volumes:
      - diariolx-postgres-data:/var/lib/postgresql/data

  diariolx-seaweed-master:
    image: chrislusf/seaweedfs:latest
    command: 'master -ip=diariolx-seaweed-master -ip.bind=0.0.0.0 -mdir=/data'
    volumes:
      - diariolx-seaweed-master-data:/data

  diariolx-seaweed-volume:
    image: chrislusf/seaweedfs:latest
    command: 'volume -mserver="diariolx-seaweed-master:9333" -ip=diariolx-seaweed-volume -ip.bind=0.0.0.0 -dir=/data'
    depends_on:
      - diariolx-seaweed-master
    volumes:
      - diariolx-seaweed-volume-data:/data

  diariolx-seaweed-filer:
    image: chrislusf/seaweedfs:latest
    command: 'filer -master="diariolx-seaweed-master:9333" -ip=diariolx-seaweed-filer -ip.bind=0.0.0.0'
    depends_on:
      - diariolx-seaweed-master
      - diariolx-seaweed-volume
    volumes:
      - diariolx-seaweed-filer-data:/data

  diariolx-seaweed-s3:
    image: chrislusf/seaweedfs:latest
    command: 's3 -filer="diariolx-seaweed-filer:8888" -ip.bind=0.0.0.0 -config=/etc/seaweedfs/seaweed-config.json'
    depends_on:
      - diariolx-seaweed-filer
    volumes:
      - ../../seaweed-config.json:/etc/seaweedfs/seaweed-config.json:ro
    ports:
      - "8335:8333"

  diariolx-seaweed-admin:
    image: chrislusf/seaweedfs:latest
    command: 'admin -port=23646 -masters="diariolx-seaweed-master:9333"'
    depends_on:
      - diariolx-seaweed-master
    ports:
      - "23646:23646"

  diariolx-jvm-dynamic:
    image: diariolx-jvm
    hostname: diariolx-jvm-dynamic
    env_file:
      - ../../.env.staging

  nginx:
    image: diariolx-nginx
    ports:
      - "8180:8180"
    depends_on:
      - diariolx-seaweed-s3
      - diariolx-jvm-dynamic

  ubuntu:
    container_name: ubuntu
    image: diariolx-ubuntu
    tty: true

volumes:
  diariolx-postgres-data:
  diariolx-seaweed-master-data:
  diariolx-seaweed-volume-data:
  diariolx-seaweed-filer-data: