FROM node:22-alpine AS frontend-build

WORKDIR /app

COPY js/package*.json ./
RUN npm ci

COPY js .
RUN npm run build

FROM nginx:alpine

COPY ./jvm/modules/host/tests/nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=frontend-build /app/dist /usr/share/nginx/html
