server.port=${PORT:8180}
scalar.path=${SCALAR_PATH:/docs}
scalar.url=/v3/api-docs
scalar.servers[0].url=${APP_PUBLIC_URL}/api
scalar.servers[0].description=Production
scalar.servers[1].url=http://localhost:8180/api
scalar.servers[1].description=Local
spring.dotenv.location=.env
server.forward-headers-strategy=framework