server.port=${port:8180}
storage.s3.endpoint=http://localhost:8333
storage.s3.region=us-east-1
storage.s3.access-key=W8MKPITOHOSYZ49IA8EB
storage.s3.secret-key=APT6woxJiphaGIi8tRCGjwmCjvkwgXO7IBL7W3qnNL
storage.s3.bucket=images
storage.s3.path-style-access=true

