FROM postgres

USER postgres
WORKDIR /app

COPY /src/sql/create-schema.sql /docker-entrypoint-initdb.d/1_create-tables.sql
COPY /src/sql/create-indexes.sql /docker-entrypoint-initdb.d/2_create-indexes.sql
COPY /src/sql/create-views.sql /docker-entrypoint-initdb.d/3_create-views.sql
COPY /src/sql/insert-test-data.sql /docker-entrypoint-initdb.d/4_insert-test-data.sql

COPY --chown=postgres:postgres ./tests/scripts/wait-for-postgres.sh ./bin/wait-for-postgres.sh
RUN chmod +x ./bin/wait-for-postgres.sh

EXPOSE 5432